new functions
Fogonrog/three-points pull request #13
Opened 2023-06-08 14:16 UTC by Fogonrog

2023-06-08 17:40 UTC, vityaman requested changes

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/LevelInfoJSON.java
> +public final class LevelInfoJSON {
Хм, мб перенести пакет serialization в корень и положить туда все такие JSON объекты и парсеры

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/logic/CampaignService.java
> +        return campaignRepository.getCampaignByName(campaignName) != null;
А можно из getCampaignByName Optional возвращать? Так будет безопаснее

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/logic/CampaignService.java
> +        return campaigns;
Этот метод можно одним стейтментом написать с помощью Stream API, кстати.

```
return campaignRepository
  .getAllCampaigns().stream()
  .map(Campaign::fromEntity)
  .toList();
```

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/logic/CampaignService.java
> +        CampaignEntity entity = new CampaignEntity(draft.id, draft.name);
Стоп, откуда у черновика кампании айдишник? Он же в бд должен генерироваться

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/logic/LevelService.java
> +        levelRepository = new LevelRepository(application);
Зачем вы передаете в конструктор приложение? Можно же просто LevelRepository дать. Кажется, что это нарушение DIP. Зависимости всегда нужно стараться принимать из конструктора, а не создавать самому. И только в самом мейне приложения инстанциировать все объекты. А потом лишь вайрить зависимости.

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/logic/model/Campaign.java
> +    public String name;
Лучше прикрыть геттерами, чтобы можно было в них в случае чего какие-то проверки добавить или логи.

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/logic/model/LevelInfo.java
> +    public boolean done;
Бан за публичные поля. Прикрыть геттерами. Если вам впадлу писать геттеры, их можно сгенерить идеей, либо заюзать библиотеку lombok.

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/logic/serialization/Parser.java
> +        } catch (IOException e) {
Лол, а откуда там это исключение летит?

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/logic/serialization/Parser.java
> +                    .replace("{{INDENT}}", String.valueOf(20));
Думаю, вот эти параметры для подстановки лучше сделать полями класса парсер, вы же будете одно и то же каждый раз в сюда пихать. А indent и вовсе захардкодили, не пойдет.

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/logic/serialization/Parser.java
> +                    .replace("{{INDENT}}", String.valueOf(20));
Дублирование кода, сделайте какой-то свой класс типа Template, в который бы передавали маппинг этих алиасов на значения.

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/CampaignRepository.java
> +        AppDatabase db = AppDatabase.getDatabase(application);
АппДатабазу инжектите в конструктор, не должна апа на этот слой проходить никак, да и не нужно в этом случае.

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/CampaignRepository.java
> +public class CampaignRepository {
Раз уж вы решили реализовывать репозиторий через dao, то давайте в них и конвертацию в доменные сущности делать будем, чтобы в бизнес логику сразу бизнес объекты прилетали

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/dao/CampaignDao.java
> +    public long insertCampaign(CampaignEntity campaignEntity);
В интерфейсах можно не писать public.
Вы точно пофиксили чекстайл? Тут, кстати, лонг это как раз будет айдишник, кажется.

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/database/AppDatabase.java
> +    }
О, шарите!

2023-06-08 17:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/entity/LevelEntity.java
> +public class LevelEntity {
Ну, тут можно паблик, наверное, оставить.

2023-06-08 19:06 UTC, Fogonrog commented on app/src/main/java/com/example/myapplication/logic/serialization/Parser.java
> +        } catch (IOException e) {
в методе readValue, могу попасть невалидные данные

2023-06-08 19:12 UTC, Fogonrog commented on app/src/main/java/com/example/myapplication/logic/CampaignService.java
> +        CampaignEntity entity = new CampaignEntity(draft.id, draft.name);
эмм, не знаю мы так договорились, когда проектировали

2023-06-08 19:14 UTC, Fogonrog commented on app/src/main/java/com/example/myapplication/logic/CampaignService.java
> +        return campaigns;
метод toList() не существует

2023-06-08 19:17 UTC, Fogonrog commented on app/src/main/java/com/example/myapplication/logic/CampaignService.java
> +        return campaignRepository.getCampaignByName(campaignName) != null;
ну тут же вся суть метода, я проверяю существует ли компания с таким именем, если она нуловая, я кидаю false, не существует

2023-06-08 19:19 UTC, Fogonrog commented on app/src/main/java/com/example/myapplication/logic/model/LevelInfo.java
> +    public boolean done;
😭

2023-06-09 18:16 UTC, vityaman requested changes

2023-06-09 18:16 UTC, vityaman commented on app/src/main/java/com/example/myapplication/logic/CampaignService.java
> +        return campaignRepository.isCampaignExists(campaignName) > 0;
Унесите это на уровень репозитория. Переименуйте метод в дао, у вас же семантика совсем другая. Пусть в дао будет каунтКампанииПоИмени, а в репозитории уже экзистс, ну емае

2023-06-09 18:16 UTC, vityaman commented on app/src/main/java/com/example/myapplication/logic/CampaignService.java
> +    }
Это очень плохо, зачем вам этот геттер, уберите, его, пожалуйста

2023-06-09 18:16 UTC, vityaman commented on app/src/main/java/com/example/myapplication/logic/LevelService.java
> +    }
Зачем?

2023-06-09 18:16 UTC, vityaman commented on app/src/main/java/com/example/myapplication/logic/LevelService.java
> +    public List<Level> getAllLevelsByCampaignId(Long campaignId, float width, float height) {
Так. Не надо так. Размеры кладите в конструктор парсера, а парсер в конструктор сервиса, это выглядит очень некрасиво

2023-06-09 18:16 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/CampaignRepository.java
> +    public int isCampaignExists(String name) {
boolean

2023-06-09 18:16 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/CampaignRepository.java
> +    public Campaign getCampaignById(long id) {
Используйте Optional, компания может быть null

2023-06-09 18:16 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/LevelRepository.java
> +    public long insertLevel(LevelEntity levelEntity) {
А тут вместо лонга можно возвращать Level. А принимать оно должно LevelDraft, кажется

2023-06-09 18:16 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/database/AppDatabase.java
> +    public static void execute(Runnable runnable) {
Это зачем?

2023-06-10 05:06 UTC, vityaman requested changes

2023-06-10 05:06 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/dao/CampaignDao.java
> +    int isCampaignExists(String name);
count

2023-06-10 09:32 UTC, vityaman requested changes

2023-06-10 09:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/logic/model/Campaign.java
> +    public static Optional<Campaign> fromEntity(CampaignEntity entity) {
нет, почему тут Optional? Тут же всегда не null

2023-06-10 09:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/CampaignRepository.java
> +    public Optional<Campaign> getCampaignById(long id) {
вот, другое дело.

2023-06-10 09:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/CampaignRepository.java
>          return Campaign.fromEntity(campaignDao.getCampaignById(id));
вы тут должны делать `campaignDao.getCampaignById(id).map(Campaign::fromEntity)`

2023-06-10 09:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/LevelRepository.java
> +            var campaignEntity = new CampaignEntity(random.nextLong(), name);
зачем же рандом? Лучше кладите какое-то заметное невалидное значение. Например -1. Рандом лишь иусугубит ситуацию, сделав сценарий невоспроизводимым.

2023-06-10 09:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/LevelRepository.java
> +        if (campaignDao.getCampaignByName(level.getCampaignName()) == null) {
getCampaignByName тоже должен возвращать `Optional`

2023-06-10 09:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/LevelRepository.java
> +        var levelEntity = new LevelEntity(id, campaignId, campaignName, number, stage, false);
что значит `false`. Передавание литералов булов в аргументы очень плохо читается, вынесите в переменную.

2023-06-10 09:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/repository/LevelRepository.java
> +        var campaignId = campaignDao.getCampaignByName(level.getCampaignName()).getId();
вы тут делаете два запроса к БД, если `campaignDao.getCampaignByName(level.getCampaignName()) == Some(...)`. Это недешевая операция. Сохраняйте результат первого вызова в переменную. Нужно минимизировать операции ввода-вывода

2023-06-10 09:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/view/activities/ChooseLevelActivity.java
> +            if (data != null) {
можно схлопунть оба ифа в 1 и понизить вложенность

2023-06-10 09:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/view/activities/ChooseLevelActivity.java
> +        if (resultCode == RESULT_OK && requestCode == 1) {
что значит `requestCode == 1`? Сделайте константу

2023-06-10 09:40 UTC, Fogonrog commented on app/src/main/java/com/example/myapplication/repository/LevelRepository.java
> +            var campaignEntity = new CampaignEntity(random.nextLong(), name);
ну так мы это уже проходили. бд не генерирует новое значение, по неизвестной мне причине

2023-06-10 14:50 UTC, merged