New graphics structure
Fogonrog/three-points pull request #7
Opened 2023-05-01 09:37 UTC by Fogonrog

2023-05-01 13:41 UTC, vityaman requested changes

2023-05-01 13:41 UTC, vityaman commented on app/build.gradle
> +        targetCompatibility JavaVersion.VERSION_1_9
А зачем вы поменяли версию Java? Может быть ее таким образом можно будет и до последней обновить, чтобы использовать современные фичи?

2023-05-01 13:41 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +    public static Function function = x;
Вижу публичные статические переменные и грущу.

2023-05-01 13:41 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +        mainCanvas.draw(axes);
Красота! Как вариант: можно тут рядышком сделать 
```
final var h = (float)getHeight();
```
и тогда читаться проще будет. И цвет тоже в переменную, но это уже не обязательно.

2023-05-01 13:41 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Expressions/Num.java
> +        }
Давайте лучше будем пользоваться `String.valueOf(int integer)` вместо `"" + number`.

2023-05-01 13:41 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Graphics/FunctionGraph.java
> +        }
Кстати, можно функцию рисовать не кружечками, а прямыми линиями. Тогда можно будет шаг немного побольше сделать и по идее это дешевле будет. Ну, то есть, будем прямую аппроксимировать ломанной.

2023-05-01 13:41 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +        mainCanvas.draw(axes);
Есть предложение сделать еще одну реализацию `Drawable`:
```
class Colored : Drawable {
  child: Drawable
  color: Color

  drawOn(canvas: Canvas): Unit {
    canvas.setColor(color)
    canvas.draw(child)
  }
}
```
Нам тогда не нужно будет хранить цвет в качестве атрибута большинства реализаций `Drawable`. Ну, и засовывать в конструкторы по сто раз не придется. Как вам идея?

```
final var axis = new Container(...);
final var redAxis = new Colored(Color.RED, axis);
final var greenAxis = new Colored(Color.GREEN, axis);
canvas.draw(redAxis);
canvas.draw(greeenAxis);
```

2023-05-01 13:41 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Graphics/Circle.java
> +    private final Float radius;
Лучше использовать примитивы, они работают быстрее. Там же boxing, помните же

2023-05-01 13:41 UTC, vityaman commented on app/src/main/java/com/example/myapplication/MyDialogFragment.java
> +            Draw2D.function = x;
Ахх, вот как вы передаете функцию в тот визуальный элемент! Так, не-не-не, так не пойдет. Это как раз то, что мешает нам использовать сразу 2 инстанса Draw2D, содержащие разные графики. Вам нужно сделать так, чтобы функция передавалась через конструктор, андроидовскую фигню какую-нибудь или на крайняк сеттер. Никаких статических переменных!

2023-05-01 13:45 UTC, Fogonrog commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +        mainCanvas.draw(axes);
Классная идея

2023-05-01 13:51 UTC, Fogonrog commented on app/build.gradle
> +        targetCompatibility JavaVersion.VERSION_1_9
Не получается((

2023-05-01 13:55 UTC, Fogonrog commented on app/build.gradle
> +        targetCompatibility JavaVersion.VERSION_1_9
А нет, вру. Получилось поменять, но только на 17. Почему то градл ругается на 10 версию

2023-05-03 15:54 UTC, vityaman requested changes

2023-05-03 15:54 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Draw2D.java
>          this.canvas = canvas;
Вообще, я имел ввиду, конечно, сделать их локальными переменными. Ведь getHeight возвращает актуальную высоту вьюшки. Предоставьте, что пользователь перевернул экран или каким-то другим способом изменил размеры этого элемента. В конце концов, мы же пишем эту вьюшку не только под нашу задача, она решает достаточно общую задачу.

2023-05-03 15:54 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Graphics/Colored.java
> +    public void drawOn(Canvas canvas) {
🥰🤩😘😜💖🔥💅🏄

2023-05-03 16:00 UTC, Fogonrog commented on app/src/main/java/com/example/myapplication/Draw2D.java
>          this.canvas = canvas;
Кстати, я запретил переворачивать экран

2023-05-03 16:45 UTC, vityaman approved these changes

2023-05-03 16:46 UTC, merged