checkup
Fogonrog/three-points pull request #9
Opened 2023-05-12 17:07 UTC by Fogonrog

2023-05-21 18:32 UTC, vityaman reviewed
Частично, потом еще добавлю

2023-05-21 18:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +    private final boolean isBigCanvas;
Это уже лучше, чем `MiniDraw2D` :)
Когда-нибудь и от этой переменной избавимся

2023-05-21 18:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +    private Line rightLine;
Это в коллекцию фигур унесем

2023-05-21 18:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +    private Polygon leftCoast;
Это и еще правый берег унесем в коллекцию драваблес

2023-05-21 18:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +        return rightLine.getJts().intersects(func.getJts()) && leftLine.getJts().intersects(func.getJts());
getJts спрячем, инкапсуляцию не нарушим
на цикл по всем препятствиям перепишем

2023-05-21 18:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +        if (axes == null) {
давайте тело ифа в отдельный метод вынесем для читаемости

2023-05-21 18:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +        var redFunc = Colored.from(Color.RED, LARGE_WIDTH, func);
в целом, можно не выносить в переменную, а сразу экспрешн подставлять
переменные обычно используют, чтобы сделать более понятным происходящее
либо для переиспользования

но в нашем случае переменная используется ровно один раз и и так видно, что это красная функция

2023-05-21 18:32 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +    private static final int LARGE_WIDTH = 8;
А напомните, зачем нам это и почему мы передаем это в аргумент `Colored`?

2023-05-21 18:36 UTC, Fogonrog commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +    private static final int LARGE_WIDTH = 8;
чтобы контролировать ширину линий

2023-05-22 07:35 UTC, vityaman requested changes
Все посмотрел

2023-05-22 07:35 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +            float width = getWidth();
Тут можно использовать var

2023-05-22 07:35 UTC, vityaman commented on app/src/main/java/com/example/myapplication/MainFragment.java
> +            inputFragment.show(manager, "myDialog");
Хм, похожий код внутри обоих обработчиков нажатий...

2023-05-22 07:35 UTC, vityaman commented on app/src/main/java/com/example/myapplication/RunFragment.java
> +        return builder.create();
Кажется, что все методы билдера возвращают инстанс билдера, чтобы можно было чейнить вызовы:
```
return new Builder()
  .setA(a)
  .setB(b)
  .build()
```

2023-05-22 07:35 UTC, vityaman commented on app/src/main/java/com/example/myapplication/graphics/BrokenLine.java
> +    private final org.locationtech.jts.geom.LineString jts;
А оба поля Line и LineString не взаимозаменяемы? Мы не можем оставить только один объект? Или лайн нам нужен для рисования, а LineString для проверки попадания?

2023-05-22 07:35 UTC, vityaman commented on app/src/main/java/com/example/myapplication/graphics/BrokenLine.java
> +    private final org.locationtech.jts.geom.LineString jts;
А оба поля Line и LineString не взаимозаменяемы? Мы не можем оставить только один объект? Или лайн нам нужен для рисования, а LineString для проверки попадания?

2023-05-22 07:35 UTC, vityaman commented on app/src/main/java/com/example/myapplication/graphics/Circle.java
> +    private final org.locationtech.jts.geom.Geometry jts;
А зачем такое полное имя? Мб просто импортнуть?..

2023-05-22 07:35 UTC, vityaman commented on app/src/main/java/com/example/myapplication/graphics/Colored.java
> +        canvas.paint.setStrokeWidth(width);
А зачем так? Вы же можете сделать декоратор, который устанавливает strokeWidth на нужное значение и не пихать width повсюду. Это точно нужно пофиксить

2023-05-22 07:35 UTC, vityaman commented on app/src/main/java/com/example/myapplication/graphics/Polygon.java
> +        for (Point point : points) {
Давайте лучше получим первую точку, сдалаем с ней то, что хотим сделать (метод для получения специальный есть скорее всего, не гет(0), а что-то вроде ферст)

А потом с помощью стрим апи сделаем скип(1) и пройдемся по остальным:
https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#skip-long-

А итератор можно назвать i, итератор и индекс - разные вещи.

2023-05-22 07:35 UTC, vityaman commented on app/src/main/res/values/strings.xml
> +    <string name="stihi">У лукоморья дуб зелёный;
Лол

2023-05-22 16:03 UTC, Fogonrog commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +        var redFunc = Colored.from(Color.RED, LARGE_WIDTH, func);
То есть вы имеет ввиду делать так?

mainCanvas.draw(Colored.from(Color.BLACK, LARGE_WIDTH, rightCoast));

2023-05-22 16:04 UTC, Fogonrog commented on app/src/main/java/com/example/myapplication/graphics/BrokenLine.java
> +    private final org.locationtech.jts.geom.LineString jts;
Нам нужны оба поля, один для отрисовки, а другой для геометрических операций

2023-05-22 16:04 UTC, Fogonrog commented on app/src/main/java/com/example/myapplication/graphics/Circle.java
> +    private final org.locationtech.jts.geom.Geometry jts;
Да, тут я тупанул

2023-05-22 16:06 UTC, Fogonrog commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +    private Polygon leftCoast;
Не совсем понимаю, зачем?

2023-05-22 16:10 UTC, Fogonrog commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +            float width = getWidth();
неа))
Point.of() принимает float, а getWidth() возвращает int. Из-за этого ide ругается

2023-05-22 18:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +    private Polygon leftCoast;
Ну а зачем, мы же всегда все вместе рисуем 
Так пусть и будет просто драваблес.форИч(канвас.драв)

2023-05-22 18:40 UTC, vityaman commented on app/src/main/java/com/example/myapplication/Draw2D.java
> +        var redFunc = Colored.from(Color.RED, LARGE_WIDTH, func);
Да

2023-05-24 18:00 UTC, merged